export const toures = [
  {
    name: 'Brazil',
    flag: 'https://ibb.co/8N3Lfhn',
  },
  {
    name: 'Belarus',
    flag: 'https://ibb.co/8N3Lfhn',
  },
  {
    name: 'Ukraine',
    flag: 'https://ibb.co/8N3Lfhn',
  },
  {
    name: 'Poland',
    flag: 'https://ibb.co/8N3Lfhn',
  },
  {
    name: 'France',
    flag: 'https://ibb.co/8N3Lfhn',
  },
];

export const rooms = [
  {
    id: 1,
    thumbnail: 'https://i.ibb.co/28P8dfF/room-preview1.jpg',
    available: false,
    title: 'The Royal Room',
    price: '₦190,000',
    review: 5,
    preview: [
      'https://i.ibb.co/RSDpND5/1607-3.jpg',
      'https://i.ibb.co/Q90Q68w/754678198272065.jpg',
      'https://i.ibb.co/q0YW4mn/9eb45e0e1c04e8871fc1081a6f18ff72.jpg',
      'https://i.ibb.co/NNWKk9Z/qaaugzhyu8cgbq1sfv6uyhyakaa8anuc.jpg',
    ],
    desc: 'This cozy furnished room with fresh renovation consists of a separate entrance hall with mirror, a bedroom with a large double bed and closet, a kitchen combined with the living room. There is also a shower cubicle and an area with sink and toilet cabinet. The windows are large so there is plenty of light in the apartment, but there are also curtains to block out unwanted light if needed. The area is very calm and quiet, in walking distance is everything you need: supermarket, bus stop, park, cinema, school, city hall.',
  },
  {
    id: 2,
    thumbnail: 'https://i.ibb.co/f4rndfx/room-preview2.jpg',
    available: true,
    title: 'The Royal Room',
    price: '₦195,000',
    review: 8,
    preview: [
      'https://i.ibb.co/RSDpND5/1607-3.jpg',
      'https://i.ibb.co/Q90Q68w/754678198272065.jpg',
      'https://i.ibb.co/q0YW4mn/9eb45e0e1c04e8871fc1081a6f18ff72.jpg',
      'https://i.ibb.co/NNWKk9Z/qaaugzhyu8cgbq1sfv6uyhyakaa8anuc.jpg',
    ],
    desc: 'This cozy furnished room with fresh renovation consists of a separate entrance hall with mirror, a bedroom with a large double bed and closet, a kitchen combined with the living room. There is also a shower cubicle and an area with sink and toilet cabinet. The windows are large so there is plenty of light in the apartment, but there are also curtains to block out unwanted light if needed. The area is very calm and quiet, in walking distance is everything you need: supermarket, bus stop, park, cinema, school, city hall.',
  },
  {
    id: 3,
    thumbnail: 'https://i.ibb.co/61FY7Ct/room-preview3.jpg',
    available: true,
    title: 'The Royal Room',
    price: '₦200,000',
    review: 6,
    preview: [
      'https://i.ibb.co/RSDpND5/1607-3.jpg',
      'https://i.ibb.co/Q90Q68w/754678198272065.jpg',
      'https://i.ibb.co/q0YW4mn/9eb45e0e1c04e8871fc1081a6f18ff72.jpg',
      'https://i.ibb.co/NNWKk9Z/qaaugzhyu8cgbq1sfv6uyhyakaa8anuc.jpg',
    ],
    desc: 'This cozy furnished room with fresh renovation consists of a separate entrance hall with mirror, a bedroom with a large double bed and closet, a kitchen combined with the living room. There is also a shower cubicle and an area with sink and toilet cabinet. The windows are large so there is plenty of light in the apartment, but there are also curtains to block out unwanted light if needed. The area is very calm and quiet, in walking distance is everything you need: supermarket, bus stop, park, cinema, school, city hall.',
  },
  {
    id: 4,
    thumbnail: 'https://i.ibb.co/f4rndfx/room-preview2.jpg',
    available: true,
    title: 'The Royal Room',
    price: '₦180,000',
    review: 5,
    preview: [
      'https://i.ibb.co/RSDpND5/1607-3.jpg',
      'https://i.ibb.co/Q90Q68w/754678198272065.jpg',
      'https://i.ibb.co/q0YW4mn/9eb45e0e1c04e8871fc1081a6f18ff72.jpg',
      'https://i.ibb.co/NNWKk9Z/qaaugzhyu8cgbq1sfv6uyhyakaa8anuc.jpg',
    ],
    desc: 'This cozy furnished room with fresh renovation consists of a separate entrance hall with mirror, a bedroom with a large double bed and closet, a kitchen combined with the living room. There is also a shower cubicle and an area with sink and toilet cabinet. The windows are large so there is plenty of light in the apartment, but there are also curtains to block out unwanted light if needed. The area is very calm and quiet, in walking distance is everything you need: supermarket, bus stop, park, cinema, school, city hall.',
  },
  {
    id: 5,
    thumbnail: 'https://i.ibb.co/RSDpND5/1607-3.jpg',
    available: true,
    title: 'The Royal Room',
    price: '₦195,000',
    review: 5,
    preview: [
      'https://i.ibb.co/61FY7Ct/room-preview3.jpg',
      'https://i.ibb.co/Q90Q68w/754678198272065.jpg',
      'https://i.ibb.co/q0YW4mn/9eb45e0e1c04e8871fc1081a6f18ff72.jpg',
      'https://i.ibb.co/NNWKk9Z/qaaugzhyu8cgbq1sfv6uyhyakaa8anuc.jpg',
    ],
    desc: 'This cozy furnished room with fresh renovation consists of a separate entrance hall with mirror, a bedroom with a large double bed and closet, a kitchen combined with the living room. There is also a shower cubicle and an area with sink and toilet cabinet. The windows are large so there is plenty of light in the apartment, but there are also curtains to block out unwanted light if needed. The area is very calm and quiet, in walking distance is everything you need: supermarket, bus stop, park, cinema, school, city hall.',
  },
  {
    id: 6,
    thumbnail: 'https://i.ibb.co/f4rndfx/room-preview2.jpg',
    available: false,
    title: 'The Royal Room',
    price: '₦200,000',
    review: 5,
    preview: [
      'https://i.ibb.co/61FY7Ct/room-preview3.jpg',
      'https://i.ibb.co/Q90Q68w/754678198272065.jpg',
      'https://i.ibb.co/q0YW4mn/9eb45e0e1c04e8871fc1081a6f18ff72.jpg',
      'https://i.ibb.co/NNWKk9Z/qaaugzhyu8cgbq1sfv6uyhyakaa8anuc.jpg',
    ],
    desc: 'This cozy furnished room with fresh renovation consists of a separate entrance hall with mirror, a bedroom with a large double bed and closet, a kitchen combined with the living room. There is also a shower cubicle and an area with sink and toilet cabinet. The windows are large so there is plenty of light in the apartment, but there are also curtains to block out unwanted light if needed. The area is very calm and quiet, in walking distance is everything you need: supermarket, bus stop, park, cinema, school, city hall.',
  },
  {
    id: 7,
    thumbnail: 'https://i.ibb.co/28P8dfF/room-preview1.jpg',
    available: true,
    title: 'The Royal Room',
    price: '₦190,000',
    review: 5,
    preview: [
      'https://i.ibb.co/61FY7Ct/room-preview3.jpg',
      'https://i.ibb.co/Q90Q68w/754678198272065.jpg',
      'https://i.ibb.co/q0YW4mn/9eb45e0e1c04e8871fc1081a6f18ff72.jpg',
      'https://i.ibb.co/NNWKk9Z/qaaugzhyu8cgbq1sfv6uyhyakaa8anuc.jpg',
    ],
    desc: 'This cozy furnished room with fresh renovation consists of a separate entrance hall with mirror, a bedroom with a large double bed and closet, a kitchen combined with the living room. There is also a shower cubicle and an area with sink and toilet cabinet. The windows are large so there is plenty of light in the apartment, but there are also curtains to block out unwanted light if needed. The area is very calm and quiet, in walking distance is everything you need: supermarket, bus stop, park, cinema, school, city hall.',
  },
  {
    id: 8,
    thumbnail: 'https://i.ibb.co/f4rndfx/room-preview2.jpg',
    available: true,
    title: 'The Royal Room',
    price: '₦195,000',
    review: 5,
    preview: [
      'https://i.ibb.co/61FY7Ct/room-preview3.jpg',
      'https://i.ibb.co/Q90Q68w/754678198272065.jpg',
      'https://i.ibb.co/q0YW4mn/9eb45e0e1c04e8871fc1081a6f18ff72.jpg',
      'https://i.ibb.co/NNWKk9Z/qaaugzhyu8cgbq1sfv6uyhyakaa8anuc.jpg',
    ],
    desc: 'This cozy furnished room with fresh renovation consists of a separate entrance hall with mirror, a bedroom with a large double bed and closet, a kitchen combined with the living room. There is also a shower cubicle and an area with sink and toilet cabinet. The windows are large so there is plenty of light in the apartment, but there are also curtains to block out unwanted light if needed. The area is very calm and quiet, in walking distance is everything you need: supermarket, bus stop, park, cinema, school, city hall.',
  },
  {
    id: 9,
    thumbnail: 'https://i.ibb.co/61FY7Ct/room-preview3.jpg',
    available: true,
    title: 'The Royal Room',
    price: '₦200,000',
    review: 5,
    preview: [
      'https://i.ibb.co/61FY7Ct/room-preview3.jpg',
      'https://i.ibb.co/Q90Q68w/754678198272065.jpg',
      'https://i.ibb.co/q0YW4mn/9eb45e0e1c04e8871fc1081a6f18ff72.jpg',
      'https://i.ibb.co/NNWKk9Z/qaaugzhyu8cgbq1sfv6uyhyakaa8anuc.jpg',
    ],
    desc: 'This cozy furnished room with fresh renovation consists of a separate entrance hall with mirror, a bedroom with a large double bed and closet, a kitchen combined with the living room. There is also a shower cubicle and an area with sink and toilet cabinet. The windows are large so there is plenty of light in the apartment, but there are also curtains to block out unwanted light if needed. The area is very calm and quiet, in walking distance is everything you need: supermarket, bus stop, park, cinema, school, city hall.',
  },
  {
    id: 10,
    thumbnail: 'https://i.ibb.co/f4rndfx/room-preview2.jpg',
    available: true,
    title: 'The Royal Room',
    price: '₦180,000',
    review: 5,
    preview: [
      'https://i.ibb.co/61FY7Ct/room-preview3.jpg',
      'https://i.ibb.co/Q90Q68w/754678198272065.jpg',
      'https://i.ibb.co/q0YW4mn/9eb45e0e1c04e8871fc1081a6f18ff72.jpg',
      'https://i.ibb.co/NNWKk9Z/qaaugzhyu8cgbq1sfv6uyhyakaa8anuc.jpg',
    ],
    desc: 'This cozy furnished room with fresh renovation consists of a separate entrance hall with mirror, a bedroom with a large double bed and closet, a kitchen combined with the living room. There is also a shower cubicle and an area with sink and toilet cabinet. The windows are large so there is plenty of light in the apartment, but there are also curtains to block out unwanted light if needed. The area is very calm and quiet, in walking distance is everything you need: supermarket, bus stop, park, cinema, school, city hall.',
  },
  {
    id: 11,
    thumbnail: 'https://i.ibb.co/61FY7Ct/room-preview3.jpg',
    available: true,
    title: 'The Royal Room',
    price: '₦195,000',
    review: 5,
    preview: [
      'https://i.ibb.co/61FY7Ct/room-preview3.jpg',
      'https://i.ibb.co/Q90Q68w/754678198272065.jpg',
      'https://i.ibb.co/q0YW4mn/9eb45e0e1c04e8871fc1081a6f18ff72.jpg',
      'https://i.ibb.co/NNWKk9Z/qaaugzhyu8cgbq1sfv6uyhyakaa8anuc.jpg',
    ],
    desc: 'This cozy furnished room with fresh renovation consists of a separate entrance hall with mirror, a bedroom with a large double bed and closet, a kitchen combined with the living room. There is also a shower cubicle and an area with sink and toilet cabinet. The windows are large so there is plenty of light in the apartment, but there are also curtains to block out unwanted light if needed. The area is very calm and quiet, in walking distance is everything you need: supermarket, bus stop, park, cinema, school, city hall.',
  },
  {
    id: 12,
    thumbnail: 'https://i.ibb.co/f4rndfx/room-preview2.jpg',
    available: true,
    title: 'The Royal Room',
    price: '₦200,000',
    review: 5,
    preview: [
      'https://i.ibb.co/61FY7Ct/room-preview3.jpg',
      'https://i.ibb.co/Q90Q68w/754678198272065.jpg',
      'https://i.ibb.co/q0YW4mn/9eb45e0e1c04e8871fc1081a6f18ff72.jpg',
      'https://i.ibb.co/NNWKk9Z/qaaugzhyu8cgbq1sfv6uyhyakaa8anuc.jpg',
    ],
    desc: 'This cozy furnished room with fresh renovation consists of a separate entrance hall with mirror, a bedroom with a large double bed and closet, a kitchen combined with the living room. There is also a shower cubicle and an area with sink and toilet cabinet. The windows are large so there is plenty of light in the apartment, but there are also curtains to block out unwanted light if needed. The area is very calm and quiet, in walking distance is everything you need: supermarket, bus stop, park, cinema, school, city hall.',
  },
  {
    id: 13,
    thumbnail: 'https://i.ibb.co/28P8dfF/room-preview1.jpg',
    available: false,
    title: 'The Royal Room',
    price: '₦190,000',
    review: 5,
    preview: [
      'https://i.ibb.co/61FY7Ct/room-preview3.jpg',
      'https://i.ibb.co/Q90Q68w/754678198272065.jpg',
      'https://i.ibb.co/q0YW4mn/9eb45e0e1c04e8871fc1081a6f18ff72.jpg',
      'https://i.ibb.co/NNWKk9Z/qaaugzhyu8cgbq1sfv6uyhyakaa8anuc.jpg',
    ],
    desc: 'This cozy furnished room with fresh renovation consists of a separate entrance hall with mirror, a bedroom with a large double bed and closet, a kitchen combined with the living room. There is also a shower cubicle and an area with sink and toilet cabinet. The windows are large so there is plenty of light in the apartment, but there are also curtains to block out unwanted light if needed. The area is very calm and quiet, in walking distance is everything you need: supermarket, bus stop, park, cinema, school, city hall.',
  },
  {
    id: 14,
    thumbnail: 'https://i.ibb.co/f4rndfx/room-preview2.jpg',
    available: true,
    title: 'The Royal Room',
    price: '₦195,000',
    review: 5,
    preview: [
      'https://i.ibb.co/61FY7Ct/room-preview3.jpg',
      'https://i.ibb.co/Q90Q68w/754678198272065.jpg',
      'https://i.ibb.co/q0YW4mn/9eb45e0e1c04e8871fc1081a6f18ff72.jpg',
      'https://i.ibb.co/NNWKk9Z/qaaugzhyu8cgbq1sfv6uyhyakaa8anuc.jpg',
    ],
    desc: 'This cozy furnished room with fresh renovation consists of a separate entrance hall with mirror, a bedroom with a large double bed and closet, a kitchen combined with the living room. There is also a shower cubicle and an area with sink and toilet cabinet. The windows are large so there is plenty of light in the apartment, but there are also curtains to block out unwanted light if needed. The area is very calm and quiet, in walking distance is everything you need: supermarket, bus stop, park, cinema, school, city hall.',
  },
  {
    id: 15,
    thumbnail: 'https://i.ibb.co/61FY7Ct/room-preview3.jpg',
    available: true,
    title: 'The Royal Room',
    price: '₦200,000',
    review: 5,
    preview: [
      'https://i.ibb.co/61FY7Ct/room-preview3.jpg',
      'https://i.ibb.co/Q90Q68w/754678198272065.jpg',
      'https://i.ibb.co/q0YW4mn/9eb45e0e1c04e8871fc1081a6f18ff72.jpg',
      'https://i.ibb.co/NNWKk9Z/qaaugzhyu8cgbq1sfv6uyhyakaa8anuc.jpg',
    ],
    desc: 'This cozy furnished room with fresh renovation consists of a separate entrance hall with mirror, a bedroom with a large double bed and closet, a kitchen combined with the living room. There is also a shower cubicle and an area with sink and toilet cabinet. The windows are large so there is plenty of light in the apartment, but there are also curtains to block out unwanted light if needed. The area is very calm and quiet, in walking distance is everything you need: supermarket, bus stop, park, cinema, school, city hall.',
  },
  {
    id: 16,
    thumbnail: 'https://i.ibb.co/f4rndfx/room-preview2.jpg',
    available: true,
    title: 'The Royal Room',
    price: '₦180,000',
    review: 5,
    preview: [
      'https://i.ibb.co/61FY7Ct/room-preview3.jpg',
      'https://i.ibb.co/Q90Q68w/754678198272065.jpg',
      'https://i.ibb.co/q0YW4mn/9eb45e0e1c04e8871fc1081a6f18ff72.jpg',
      'https://i.ibb.co/NNWKk9Z/qaaugzhyu8cgbq1sfv6uyhyakaa8anuc.jpg',
    ],
    desc: 'This cozy furnished room with fresh renovation consists of a separate entrance hall with mirror, a bedroom with a large double bed and closet, a kitchen combined with the living room. There is also a shower cubicle and an area with sink and toilet cabinet. The windows are large so there is plenty of light in the apartment, but there are also curtains to block out unwanted light if needed. The area is very calm and quiet, in walking distance is everything you need: supermarket, bus stop, park, cinema, school, city hall.',
  },
  {
    id: 17,
    thumbnail: 'https://i.ibb.co/61FY7Ct/room-preview3.jpg',
    available: true,
    title: 'The Royal Room',
    price: '₦195,000',
    review: 5,
    preview: [
      'https://i.ibb.co/61FY7Ct/room-preview3.jpg',
      'https://i.ibb.co/Q90Q68w/754678198272065.jpg',
      'https://i.ibb.co/q0YW4mn/9eb45e0e1c04e8871fc1081a6f18ff72.jpg',
      'https://i.ibb.co/NNWKk9Z/qaaugzhyu8cgbq1sfv6uyhyakaa8anuc.jpg',
    ],
    desc: 'This cozy furnished room with fresh renovation consists of a separate entrance hall with mirror, a bedroom with a large double bed and closet, a kitchen combined with the living room. There is also a shower cubicle and an area with sink and toilet cabinet. The windows are large so there is plenty of light in the apartment, but there are also curtains to block out unwanted light if needed. The area is very calm and quiet, in walking distance is everything you need: supermarket, bus stop, park, cinema, school, city hall.',
  },
  {
    id: 18,
    thumbnail: 'https://i.ibb.co/f4rndfx/room-preview2.jpg',
    available: false,
    title: 'The Royal Room',
    price: '₦200,000',
    review: 5,
    preview: [
      'https://i.ibb.co/61FY7Ct/room-preview3.jpg',
      'https://i.ibb.co/Q90Q68w/754678198272065.jpg',
      'https://i.ibb.co/q0YW4mn/9eb45e0e1c04e8871fc1081a6f18ff72.jpg',
      'https://i.ibb.co/NNWKk9Z/qaaugzhyu8cgbq1sfv6uyhyakaa8anuc.jpg',
    ],
    desc: 'This cozy furnished room with fresh renovation consists of a separate entrance hall with mirror, a bedroom with a large double bed and closet, a kitchen combined with the living room. There is also a shower cubicle and an area with sink and toilet cabinet. The windows are large so there is plenty of light in the apartment, but there are also curtains to block out unwanted light if needed. The area is very calm and quiet, in walking distance is everything you need: supermarket, bus stop, park, cinema, school, city hall.',
  },
  {
    id: 19,
    thumbnail: 'https://i.ibb.co/28P8dfF/room-preview1.jpg',
    available: true,
    title: 'The Royal Room',
    price: '₦190,000',
    review: 5,
    preview: [
      'https://i.ibb.co/61FY7Ct/room-preview3.jpg',
      'https://i.ibb.co/Q90Q68w/754678198272065.jpg',
      'https://i.ibb.co/q0YW4mn/9eb45e0e1c04e8871fc1081a6f18ff72.jpg',
      'https://i.ibb.co/NNWKk9Z/qaaugzhyu8cgbq1sfv6uyhyakaa8anuc.jpg',
    ],
    desc: 'This cozy furnished room with fresh renovation consists of a separate entrance hall with mirror, a bedroom with a large double bed and closet, a kitchen combined with the living room. There is also a shower cubicle and an area with sink and toilet cabinet. The windows are large so there is plenty of light in the apartment, but there are also curtains to block out unwanted light if needed. The area is very calm and quiet, in walking distance is everything you need: supermarket, bus stop, park, cinema, school, city hall.',
  },
  {
    id: 20,
    thumbnail: 'https://i.ibb.co/f4rndfx/room-preview2.jpg',
    available: true,
    title: 'The Royal Room',
    price: '₦195,000',
    review: 5,
    preview: [
      'https://i.ibb.co/61FY7Ct/room-preview3.jpg',
      'https://i.ibb.co/Q90Q68w/754678198272065.jpg',
      'https://i.ibb.co/q0YW4mn/9eb45e0e1c04e8871fc1081a6f18ff72.jpg',
      'https://i.ibb.co/NNWKk9Z/qaaugzhyu8cgbq1sfv6uyhyakaa8anuc.jpg',
    ],
    desc: 'This cozy furnished room with fresh renovation consists of a separate entrance hall with mirror, a bedroom with a large double bed and closet, a kitchen combined with the living room. There is also a shower cubicle and an area with sink and toilet cabinet. The windows are large so there is plenty of light in the apartment, but there are also curtains to block out unwanted light if needed. The area is very calm and quiet, in walking distance is everything you need: supermarket, bus stop, park, cinema, school, city hall.',
  },
  {
    id: 21,
    thumbnail: 'https://i.ibb.co/61FY7Ct/room-preview3.jpg',
    available: true,
    title: 'The Royal Room',
    price: '₦200,000',
    review: 5,
    preview: [
      'https://i.ibb.co/61FY7Ct/room-preview3.jpg',
      'https://i.ibb.co/Q90Q68w/754678198272065.jpg',
      'https://i.ibb.co/q0YW4mn/9eb45e0e1c04e8871fc1081a6f18ff72.jpg',
      'https://i.ibb.co/NNWKk9Z/qaaugzhyu8cgbq1sfv6uyhyakaa8anuc.jpg',
    ],
    desc: 'This cozy furnished room with fresh renovation consists of a separate entrance hall with mirror, a bedroom with a large double bed and closet, a kitchen combined with the living room. There is also a shower cubicle and an area with sink and toilet cabinet. The windows are large so there is plenty of light in the apartment, but there are also curtains to block out unwanted light if needed. The area is very calm and quiet, in walking distance is everything you need: supermarket, bus stop, park, cinema, school, city hall.',
  },
];
