export const toures = [
  {
    currency: 'BRL',
    name: 'Brazil',
    flag: 'https://i.ibb.co/w0McCzG/1200px-Flag-of-Brazil-svg.png',
    language: 'Portuguese',
    toure: 'Tour of Brazil', 
  },
  {
    currency: 'BYN',
    name: 'Belarus',
    flag: 'https://i.ibb.co/7CcdJcV/Flag-of-Belarus-svg.png',
    language: 'Belarusian',
    toure: 'Tour of Belarus', 
  },
  {
    currency: 'AED',
    name: 'United Arab Emirates',
    flag: 'https://i.ibb.co/bKRLZX4/Flag-of-the-United-Arab-Emirates-svg.png',
    language: 'Arabic',
    toure: 'Tour of United Arab Emirates', 
  },
  {
    currency: 'AMD',
    name: 'Armenia',
    flag: 'https://i.ibb.co/bBX3HV0/Flag-of-Armenia-svg.png',
    language: 'Armenian',
    toure: 'Tour of Armenia', 
  },
  {
    currency: 'ARS',
    name: 'Argentina',
    flag: 'https://i.ibb.co/JmTht3y/Flag-of-Argentina-svg.png',
    language: 'Spanish',
    toure: 'Tour of Argentina', 
  },
  {
    currency: 'EUR',
    name: 'Austria',
    flag: 'https://i.ibb.co/f9t8myX/Flag-of-Austria-svg.png',
    language: 'German',
    toure: 'Tour of Austria', 
  },
  {
    currency: 'CAD',
    name: 'Canada',
    flag: 'https://i.ibb.co/dMXRz8F/istockphoto-1414559861-612x612.jpg',
    language: 'English',
    toure: 'Tour of Canada', 
  },
  {
    currency: 'EUR',
    name: 'Cyprus',
    flag: 'https://i.ibb.co/y4Cs4B4/Cyprus-flag-300.png',
    language: 'Greek',
    toure: 'Tour of Cyprus', 
  },
  {
    currency: 'EUR',
    name: 'Germany',
    flag: 'https://i.ibb.co/7VvVpv4/Flag-of-Germany-svg.png',
    language: 'German',
    toure: 'Tour of Germany', 
  },
  {
    currency: 'EUR',
    name: 'Estonia',
    flag: 'https://i.ibb.co/ssstWMm/Flag-of-Estonia-svg.png',
    language: 'Estonian',
    toure: 'Tour of Estonia', 
  },
  {
    currency: 'EUR',
    name: 'Finland',
    flag: 'https://i.ibb.co/phPkWMp/Flag-of-Finland-svg.png',
    language: 'Finnish',
    toure: 'Tour of Finland', 
  },
  {
    currency: 'EUR',
    name: 'France',
    flag: 'https://i.ibb.co/GCSSJ5s/Flag-of-France-svg.png',
    language: 'French',
    toure: 'Tour of France', 
  },
  {
    currency: 'GEL',
    name: 'Georgia',
    flag: 'https://i.ibb.co/j5gF4C5/Flag-of-Georgia-svg.png',
    language: 'Georgian',
    toure: 'Tour of Georgia', 
  },
  {
    currency: 'EUR',
    name: 'Italy',
    flag: 'https://i.ibb.co/cQYVxgs/Flag-of-Italy-svg.png',
    language: 'Italian',
    toure: 'Tour of Italy', 
  },
  {
    currency: 'KZT',
    name: 'Kazakhstan',
    flag: 'https://i.ibb.co/dKHtLY2/Flag-of-Kazakhstan-svg.png',
    language: 'Kazakh',
    toure: 'Tour of Kazakhstan', 
  },
  {
    currency: 'EUR',
    name: 'Lithuania',
    flag: 'https://i.ibb.co/GcV1VC8/Flag-of-Lithuania-svg.png',
    language: 'Lithuanian',
    toure: 'Tour of Lithuania', 
  },
  {
    currency: 'EUR',
    name: 'Latvia',
    flag: 'https://i.ibb.co/LkjmBr6/Flag-of-Latvia-svg.png',
    language: 'Latvian',
    toure: 'Tour of Latvia', 
  },
  {
    currency: 'MDL',
    name: 'Moldova',
    flag: 'https://i.ibb.co/ZKPJ8XY/Flag-of-Moldova-svg.png',
    language: 'Romanian',
    toure: 'Tour of Moldova', 
  },
  {
    currency: 'PLN',
    name: 'Poland',
    flag: 'https://i.ibb.co/c6nKp0M/Flag-of-Poland-svg-1.webp',
    language: 'Polish',
    toure: 'Tour of Poland', 
  },
  {
    currency: 'RSD',
    name: 'Serbia',
    flag: 'https://i.ibb.co/7JrJsPZ/Flag-of-Serbia-svg.png',
    language: 'Serbian',
    toure: 'Tour of Serbia', 
  },
  {
    currency: 'SEK',
    name: 'Sweden',
    flag: 'https://i.ibb.co/x5YkrbV/Flag-of-Sweden-svg.webp',
    language: 'Swedish',
    toure: 'Tour of Sweden', 
  },
];

export const rooms = [
  {
    id: 1,
    thumbnail: 'https://i.ibb.co/28P8dfF/room-preview1.jpg',
    available: false,
    title: 'The Royal Room',
    price: '₦190,000',
    review: 5,
    preview: [
      'https://i.ibb.co/RSDpND5/1607-3.jpg',
      'https://i.ibb.co/Q90Q68w/754678198272065.jpg',
      'https://i.ibb.co/q0YW4mn/9eb45e0e1c04e8871fc1081a6f18ff72.jpg',
      'https://i.ibb.co/NNWKk9Z/qaaugzhyu8cgbq1sfv6uyhyakaa8anuc.jpg',
    ],
    desc: 'This cozy furnished room with fresh renovation consists of a separate entrance hall with mirror, a bedroom with a large double bed and closet, a kitchen combined with the living room. There is also a shower cubicle and an area with sink and toilet cabinet. The windows are large so there is plenty of light in the apartment, but there are also curtains to block out unwanted light if needed. The area is very calm and quiet, in walking distance is everything you need: supermarket, bus stop, park, cinema, school, city hall.',
  },
  {
    id: 2,
    thumbnail: 'https://i.ibb.co/f4rndfx/room-preview2.jpg',
    available: true,
    title: 'The Royal Room',
    price: '₦195,000',
    review: 8,
    preview: [
      'https://i.ibb.co/RSDpND5/1607-3.jpg',
      'https://i.ibb.co/Q90Q68w/754678198272065.jpg',
      'https://i.ibb.co/q0YW4mn/9eb45e0e1c04e8871fc1081a6f18ff72.jpg',
      'https://i.ibb.co/NNWKk9Z/qaaugzhyu8cgbq1sfv6uyhyakaa8anuc.jpg',
    ],
    desc: 'This cozy furnished room with fresh renovation consists of a separate entrance hall with mirror, a bedroom with a large double bed and closet, a kitchen combined with the living room. There is also a shower cubicle and an area with sink and toilet cabinet. The windows are large so there is plenty of light in the apartment, but there are also curtains to block out unwanted light if needed. The area is very calm and quiet, in walking distance is everything you need: supermarket, bus stop, park, cinema, school, city hall.',
  },
  {
    id: 3,
    thumbnail: 'https://i.ibb.co/61FY7Ct/room-preview3.jpg',
    available: true,
    title: 'The Royal Room',
    price: '₦200,000',
    review: 6,
    preview: [
      'https://i.ibb.co/RSDpND5/1607-3.jpg',
      'https://i.ibb.co/Q90Q68w/754678198272065.jpg',
      'https://i.ibb.co/q0YW4mn/9eb45e0e1c04e8871fc1081a6f18ff72.jpg',
      'https://i.ibb.co/NNWKk9Z/qaaugzhyu8cgbq1sfv6uyhyakaa8anuc.jpg',
    ],
    desc: 'This cozy furnished room with fresh renovation consists of a separate entrance hall with mirror, a bedroom with a large double bed and closet, a kitchen combined with the living room. There is also a shower cubicle and an area with sink and toilet cabinet. The windows are large so there is plenty of light in the apartment, but there are also curtains to block out unwanted light if needed. The area is very calm and quiet, in walking distance is everything you need: supermarket, bus stop, park, cinema, school, city hall.',
  },
  {
    id: 4,
    thumbnail: 'https://i.ibb.co/f4rndfx/room-preview2.jpg',
    available: true,
    title: 'The Royal Room',
    price: '₦180,000',
    review: 5,
    preview: [
      'https://i.ibb.co/RSDpND5/1607-3.jpg',
      'https://i.ibb.co/Q90Q68w/754678198272065.jpg',
      'https://i.ibb.co/q0YW4mn/9eb45e0e1c04e8871fc1081a6f18ff72.jpg',
      'https://i.ibb.co/NNWKk9Z/qaaugzhyu8cgbq1sfv6uyhyakaa8anuc.jpg',
    ],
    desc: 'This cozy furnished room with fresh renovation consists of a separate entrance hall with mirror, a bedroom with a large double bed and closet, a kitchen combined with the living room. There is also a shower cubicle and an area with sink and toilet cabinet. The windows are large so there is plenty of light in the apartment, but there are also curtains to block out unwanted light if needed. The area is very calm and quiet, in walking distance is everything you need: supermarket, bus stop, park, cinema, school, city hall.',
  },
  {
    id: 5,
    thumbnail: 'https://i.ibb.co/RSDpND5/1607-3.jpg',
    available: true,
    title: 'The Royal Room',
    price: '₦195,000',
    review: 5,
    preview: [
      'https://i.ibb.co/61FY7Ct/room-preview3.jpg',
      'https://i.ibb.co/Q90Q68w/754678198272065.jpg',
      'https://i.ibb.co/q0YW4mn/9eb45e0e1c04e8871fc1081a6f18ff72.jpg',
      'https://i.ibb.co/NNWKk9Z/qaaugzhyu8cgbq1sfv6uyhyakaa8anuc.jpg',
    ],
    desc: 'This cozy furnished room with fresh renovation consists of a separate entrance hall with mirror, a bedroom with a large double bed and closet, a kitchen combined with the living room. There is also a shower cubicle and an area with sink and toilet cabinet. The windows are large so there is plenty of light in the apartment, but there are also curtains to block out unwanted light if needed. The area is very calm and quiet, in walking distance is everything you need: supermarket, bus stop, park, cinema, school, city hall.',
  },
  {
    id: 6,
    thumbnail: 'https://i.ibb.co/f4rndfx/room-preview2.jpg',
    available: false,
    title: 'The Royal Room',
    price: '₦200,000',
    review: 5,
    preview: [
      'https://i.ibb.co/61FY7Ct/room-preview3.jpg',
      'https://i.ibb.co/Q90Q68w/754678198272065.jpg',
      'https://i.ibb.co/q0YW4mn/9eb45e0e1c04e8871fc1081a6f18ff72.jpg',
      'https://i.ibb.co/NNWKk9Z/qaaugzhyu8cgbq1sfv6uyhyakaa8anuc.jpg',
    ],
    desc: 'This cozy furnished room with fresh renovation consists of a separate entrance hall with mirror, a bedroom with a large double bed and closet, a kitchen combined with the living room. There is also a shower cubicle and an area with sink and toilet cabinet. The windows are large so there is plenty of light in the apartment, but there are also curtains to block out unwanted light if needed. The area is very calm and quiet, in walking distance is everything you need: supermarket, bus stop, park, cinema, school, city hall.',
  },
  {
    id: 7,
    thumbnail: 'https://i.ibb.co/28P8dfF/room-preview1.jpg',
    available: true,
    title: 'The Royal Room',
    price: '₦190,000',
    review: 5,
    preview: [
      'https://i.ibb.co/61FY7Ct/room-preview3.jpg',
      'https://i.ibb.co/Q90Q68w/754678198272065.jpg',
      'https://i.ibb.co/q0YW4mn/9eb45e0e1c04e8871fc1081a6f18ff72.jpg',
      'https://i.ibb.co/NNWKk9Z/qaaugzhyu8cgbq1sfv6uyhyakaa8anuc.jpg',
    ],
    desc: 'This cozy furnished room with fresh renovation consists of a separate entrance hall with mirror, a bedroom with a large double bed and closet, a kitchen combined with the living room. There is also a shower cubicle and an area with sink and toilet cabinet. The windows are large so there is plenty of light in the apartment, but there are also curtains to block out unwanted light if needed. The area is very calm and quiet, in walking distance is everything you need: supermarket, bus stop, park, cinema, school, city hall.',
  },
  {
    id: 8,
    thumbnail: 'https://i.ibb.co/f4rndfx/room-preview2.jpg',
    available: true,
    title: 'The Royal Room',
    price: '₦195,000',
    review: 5,
    preview: [
      'https://i.ibb.co/61FY7Ct/room-preview3.jpg',
      'https://i.ibb.co/Q90Q68w/754678198272065.jpg',
      'https://i.ibb.co/q0YW4mn/9eb45e0e1c04e8871fc1081a6f18ff72.jpg',
      'https://i.ibb.co/NNWKk9Z/qaaugzhyu8cgbq1sfv6uyhyakaa8anuc.jpg',
    ],
    desc: 'This cozy furnished room with fresh renovation consists of a separate entrance hall with mirror, a bedroom with a large double bed and closet, a kitchen combined with the living room. There is also a shower cubicle and an area with sink and toilet cabinet. The windows are large so there is plenty of light in the apartment, but there are also curtains to block out unwanted light if needed. The area is very calm and quiet, in walking distance is everything you need: supermarket, bus stop, park, cinema, school, city hall.',
  },
  {
    id: 9,
    thumbnail: 'https://i.ibb.co/61FY7Ct/room-preview3.jpg',
    available: true,
    title: 'The Royal Room',
    price: '₦200,000',
    review: 5,
    preview: [
      'https://i.ibb.co/61FY7Ct/room-preview3.jpg',
      'https://i.ibb.co/Q90Q68w/754678198272065.jpg',
      'https://i.ibb.co/q0YW4mn/9eb45e0e1c04e8871fc1081a6f18ff72.jpg',
      'https://i.ibb.co/NNWKk9Z/qaaugzhyu8cgbq1sfv6uyhyakaa8anuc.jpg',
    ],
    desc: 'This cozy furnished room with fresh renovation consists of a separate entrance hall with mirror, a bedroom with a large double bed and closet, a kitchen combined with the living room. There is also a shower cubicle and an area with sink and toilet cabinet. The windows are large so there is plenty of light in the apartment, but there are also curtains to block out unwanted light if needed. The area is very calm and quiet, in walking distance is everything you need: supermarket, bus stop, park, cinema, school, city hall.',
  },
  {
    id: 10,
    thumbnail: 'https://i.ibb.co/f4rndfx/room-preview2.jpg',
    available: true,
    title: 'The Royal Room',
    price: '₦180,000',
    review: 5,
    preview: [
      'https://i.ibb.co/61FY7Ct/room-preview3.jpg',
      'https://i.ibb.co/Q90Q68w/754678198272065.jpg',
      'https://i.ibb.co/q0YW4mn/9eb45e0e1c04e8871fc1081a6f18ff72.jpg',
      'https://i.ibb.co/NNWKk9Z/qaaugzhyu8cgbq1sfv6uyhyakaa8anuc.jpg',
    ],
    desc: 'This cozy furnished room with fresh renovation consists of a separate entrance hall with mirror, a bedroom with a large double bed and closet, a kitchen combined with the living room. There is also a shower cubicle and an area with sink and toilet cabinet. The windows are large so there is plenty of light in the apartment, but there are also curtains to block out unwanted light if needed. The area is very calm and quiet, in walking distance is everything you need: supermarket, bus stop, park, cinema, school, city hall.',
  },
  {
    id: 11,
    thumbnail: 'https://i.ibb.co/61FY7Ct/room-preview3.jpg',
    available: true,
    title: 'The Royal Room',
    price: '₦195,000',
    review: 5,
    preview: [
      'https://i.ibb.co/61FY7Ct/room-preview3.jpg',
      'https://i.ibb.co/Q90Q68w/754678198272065.jpg',
      'https://i.ibb.co/q0YW4mn/9eb45e0e1c04e8871fc1081a6f18ff72.jpg',
      'https://i.ibb.co/NNWKk9Z/qaaugzhyu8cgbq1sfv6uyhyakaa8anuc.jpg',
    ],
    desc: 'This cozy furnished room with fresh renovation consists of a separate entrance hall with mirror, a bedroom with a large double bed and closet, a kitchen combined with the living room. There is also a shower cubicle and an area with sink and toilet cabinet. The windows are large so there is plenty of light in the apartment, but there are also curtains to block out unwanted light if needed. The area is very calm and quiet, in walking distance is everything you need: supermarket, bus stop, park, cinema, school, city hall.',
  },
  {
    id: 12,
    thumbnail: 'https://i.ibb.co/f4rndfx/room-preview2.jpg',
    available: true,
    title: 'The Royal Room',
    price: '₦200,000',
    review: 5,
    preview: [
      'https://i.ibb.co/61FY7Ct/room-preview3.jpg',
      'https://i.ibb.co/Q90Q68w/754678198272065.jpg',
      'https://i.ibb.co/q0YW4mn/9eb45e0e1c04e8871fc1081a6f18ff72.jpg',
      'https://i.ibb.co/NNWKk9Z/qaaugzhyu8cgbq1sfv6uyhyakaa8anuc.jpg',
    ],
    desc: 'This cozy furnished room with fresh renovation consists of a separate entrance hall with mirror, a bedroom with a large double bed and closet, a kitchen combined with the living room. There is also a shower cubicle and an area with sink and toilet cabinet. The windows are large so there is plenty of light in the apartment, but there are also curtains to block out unwanted light if needed. The area is very calm and quiet, in walking distance is everything you need: supermarket, bus stop, park, cinema, school, city hall.',
  },
  {
    id: 13,
    thumbnail: 'https://i.ibb.co/28P8dfF/room-preview1.jpg',
    available: false,
    title: 'The Royal Room',
    price: '₦190,000',
    review: 5,
    preview: [
      'https://i.ibb.co/61FY7Ct/room-preview3.jpg',
      'https://i.ibb.co/Q90Q68w/754678198272065.jpg',
      'https://i.ibb.co/q0YW4mn/9eb45e0e1c04e8871fc1081a6f18ff72.jpg',
      'https://i.ibb.co/NNWKk9Z/qaaugzhyu8cgbq1sfv6uyhyakaa8anuc.jpg',
    ],
    desc: 'This cozy furnished room with fresh renovation consists of a separate entrance hall with mirror, a bedroom with a large double bed and closet, a kitchen combined with the living room. There is also a shower cubicle and an area with sink and toilet cabinet. The windows are large so there is plenty of light in the apartment, but there are also curtains to block out unwanted light if needed. The area is very calm and quiet, in walking distance is everything you need: supermarket, bus stop, park, cinema, school, city hall.',
  },
  {
    id: 14,
    thumbnail: 'https://i.ibb.co/f4rndfx/room-preview2.jpg',
    available: true,
    title: 'The Royal Room',
    price: '₦195,000',
    review: 5,
    preview: [
      'https://i.ibb.co/61FY7Ct/room-preview3.jpg',
      'https://i.ibb.co/Q90Q68w/754678198272065.jpg',
      'https://i.ibb.co/q0YW4mn/9eb45e0e1c04e8871fc1081a6f18ff72.jpg',
      'https://i.ibb.co/NNWKk9Z/qaaugzhyu8cgbq1sfv6uyhyakaa8anuc.jpg',
    ],
    desc: 'This cozy furnished room with fresh renovation consists of a separate entrance hall with mirror, a bedroom with a large double bed and closet, a kitchen combined with the living room. There is also a shower cubicle and an area with sink and toilet cabinet. The windows are large so there is plenty of light in the apartment, but there are also curtains to block out unwanted light if needed. The area is very calm and quiet, in walking distance is everything you need: supermarket, bus stop, park, cinema, school, city hall.',
  },
  {
    id: 15,
    thumbnail: 'https://i.ibb.co/61FY7Ct/room-preview3.jpg',
    available: true,
    title: 'The Royal Room',
    price: '₦200,000',
    review: 5,
    preview: [
      'https://i.ibb.co/61FY7Ct/room-preview3.jpg',
      'https://i.ibb.co/Q90Q68w/754678198272065.jpg',
      'https://i.ibb.co/q0YW4mn/9eb45e0e1c04e8871fc1081a6f18ff72.jpg',
      'https://i.ibb.co/NNWKk9Z/qaaugzhyu8cgbq1sfv6uyhyakaa8anuc.jpg',
    ],
    desc: 'This cozy furnished room with fresh renovation consists of a separate entrance hall with mirror, a bedroom with a large double bed and closet, a kitchen combined with the living room. There is also a shower cubicle and an area with sink and toilet cabinet. The windows are large so there is plenty of light in the apartment, but there are also curtains to block out unwanted light if needed. The area is very calm and quiet, in walking distance is everything you need: supermarket, bus stop, park, cinema, school, city hall.',
  },
  {
    id: 16,
    thumbnail: 'https://i.ibb.co/f4rndfx/room-preview2.jpg',
    available: true,
    title: 'The Royal Room',
    price: '₦180,000',
    review: 5,
    preview: [
      'https://i.ibb.co/61FY7Ct/room-preview3.jpg',
      'https://i.ibb.co/Q90Q68w/754678198272065.jpg',
      'https://i.ibb.co/q0YW4mn/9eb45e0e1c04e8871fc1081a6f18ff72.jpg',
      'https://i.ibb.co/NNWKk9Z/qaaugzhyu8cgbq1sfv6uyhyakaa8anuc.jpg',
    ],
    desc: 'This cozy furnished room with fresh renovation consists of a separate entrance hall with mirror, a bedroom with a large double bed and closet, a kitchen combined with the living room. There is also a shower cubicle and an area with sink and toilet cabinet. The windows are large so there is plenty of light in the apartment, but there are also curtains to block out unwanted light if needed. The area is very calm and quiet, in walking distance is everything you need: supermarket, bus stop, park, cinema, school, city hall.',
  },
  {
    id: 17,
    thumbnail: 'https://i.ibb.co/61FY7Ct/room-preview3.jpg',
    available: true,
    title: 'The Royal Room',
    price: '₦195,000',
    review: 5,
    preview: [
      'https://i.ibb.co/61FY7Ct/room-preview3.jpg',
      'https://i.ibb.co/Q90Q68w/754678198272065.jpg',
      'https://i.ibb.co/q0YW4mn/9eb45e0e1c04e8871fc1081a6f18ff72.jpg',
      'https://i.ibb.co/NNWKk9Z/qaaugzhyu8cgbq1sfv6uyhyakaa8anuc.jpg',
    ],
    desc: 'This cozy furnished room with fresh renovation consists of a separate entrance hall with mirror, a bedroom with a large double bed and closet, a kitchen combined with the living room. There is also a shower cubicle and an area with sink and toilet cabinet. The windows are large so there is plenty of light in the apartment, but there are also curtains to block out unwanted light if needed. The area is very calm and quiet, in walking distance is everything you need: supermarket, bus stop, park, cinema, school, city hall.',
  },
  {
    id: 18,
    thumbnail: 'https://i.ibb.co/f4rndfx/room-preview2.jpg',
    available: false,
    title: 'The Royal Room',
    price: '₦200,000',
    review: 5,
    preview: [
      'https://i.ibb.co/61FY7Ct/room-preview3.jpg',
      'https://i.ibb.co/Q90Q68w/754678198272065.jpg',
      'https://i.ibb.co/q0YW4mn/9eb45e0e1c04e8871fc1081a6f18ff72.jpg',
      'https://i.ibb.co/NNWKk9Z/qaaugzhyu8cgbq1sfv6uyhyakaa8anuc.jpg',
    ],
    desc: 'This cozy furnished room with fresh renovation consists of a separate entrance hall with mirror, a bedroom with a large double bed and closet, a kitchen combined with the living room. There is also a shower cubicle and an area with sink and toilet cabinet. The windows are large so there is plenty of light in the apartment, but there are also curtains to block out unwanted light if needed. The area is very calm and quiet, in walking distance is everything you need: supermarket, bus stop, park, cinema, school, city hall.',
  },
  {
    id: 19,
    thumbnail: 'https://i.ibb.co/28P8dfF/room-preview1.jpg',
    available: true,
    title: 'The Royal Room',
    price: '₦190,000',
    review: 5,
    preview: [
      'https://i.ibb.co/61FY7Ct/room-preview3.jpg',
      'https://i.ibb.co/Q90Q68w/754678198272065.jpg',
      'https://i.ibb.co/q0YW4mn/9eb45e0e1c04e8871fc1081a6f18ff72.jpg',
      'https://i.ibb.co/NNWKk9Z/qaaugzhyu8cgbq1sfv6uyhyakaa8anuc.jpg',
    ],
    desc: 'This cozy furnished room with fresh renovation consists of a separate entrance hall with mirror, a bedroom with a large double bed and closet, a kitchen combined with the living room. There is also a shower cubicle and an area with sink and toilet cabinet. The windows are large so there is plenty of light in the apartment, but there are also curtains to block out unwanted light if needed. The area is very calm and quiet, in walking distance is everything you need: supermarket, bus stop, park, cinema, school, city hall.',
  },
  {
    id: 20,
    thumbnail: 'https://i.ibb.co/f4rndfx/room-preview2.jpg',
    available: true,
    title: 'The Royal Room',
    price: '₦195,000',
    review: 5,
    preview: [
      'https://i.ibb.co/61FY7Ct/room-preview3.jpg',
      'https://i.ibb.co/Q90Q68w/754678198272065.jpg',
      'https://i.ibb.co/q0YW4mn/9eb45e0e1c04e8871fc1081a6f18ff72.jpg',
      'https://i.ibb.co/NNWKk9Z/qaaugzhyu8cgbq1sfv6uyhyakaa8anuc.jpg',
    ],
    desc: 'This cozy furnished room with fresh renovation consists of a separate entrance hall with mirror, a bedroom with a large double bed and closet, a kitchen combined with the living room. There is also a shower cubicle and an area with sink and toilet cabinet. The windows are large so there is plenty of light in the apartment, but there are also curtains to block out unwanted light if needed. The area is very calm and quiet, in walking distance is everything you need: supermarket, bus stop, park, cinema, school, city hall.',
  },
  {
    id: 21,
    thumbnail: 'https://i.ibb.co/61FY7Ct/room-preview3.jpg',
    available: true,
    title: 'The Royal Room',
    price: '₦200,000',
    review: 5,
    preview: [
      'https://i.ibb.co/61FY7Ct/room-preview3.jpg',
      'https://i.ibb.co/Q90Q68w/754678198272065.jpg',
      'https://i.ibb.co/q0YW4mn/9eb45e0e1c04e8871fc1081a6f18ff72.jpg',
      'https://i.ibb.co/NNWKk9Z/qaaugzhyu8cgbq1sfv6uyhyakaa8anuc.jpg',
    ],
    desc: 'This cozy furnished room with fresh renovation consists of a separate entrance hall with mirror, a bedroom with a large double bed and closet, a kitchen combined with the living room. There is also a shower cubicle and an area with sink and toilet cabinet. The windows are large so there is plenty of light in the apartment, but there are also curtains to block out unwanted light if needed. The area is very calm and quiet, in walking distance is everything you need: supermarket, bus stop, park, cinema, school, city hall.',
  },
];
